# Generated by Django 5.0 on 2023-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0002_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_org',
            field=models.CharField(choices=[('5', 'Boshqarma'), ('2', 'Prezident'), ('4', 'Xalq talimi vazirligi'), ('1', 'Parlament'), ('3', 'Vazirlar mahkamasi')], max_length=25, verbose_name='Tashkilot/Organisation'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_type',
            field=models.CharField(choices=[('3', 'Farmoyish'), ('1', 'Qonun'), ('2', 'Qaror'), ('5', 'Farmon'), ('4', 'Buyruq')], max_length=15, verbose_name='Toifa/Type'),
        ),
    ]
