# Generated by Django 5.0 on 2023-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_piar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery')),
            ],
            options={
                'db_table': 'gallery_images',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name_uz', models.CharField(max_length=100, verbose_name='Vakansiya nomi')),
                ('vacancy_name_en', models.CharField(max_length=100, verbose_name='Vacancy name')),
                ('vacancy_name_ru', models.CharField(max_length=100, verbose_name='Названия ваканcия')),
                ('vacancy_desc_uz', models.CharField(max_length=500, verbose_name='Vakansiya qisqacha tavsifi')),
                ('vacancy_desc_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Vacancy description')),
                ('vacancy_desc_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание вакансия')),
                ('vacancy_text_uz', models.TextField(verbose_name='Vakansiya to‘liq tavsifi')),
                ('vacancy_text_en', models.TextField(blank=True, null=True, verbose_name='Vacancy full text')),
                ('vacancy_text_ru', models.TextField(blank=True, null=True, verbose_name='Польное описания вакансия')),
                ('vacancy_datetime', models.DateTimeField(auto_now_add=True)),
                ('vacancy_views_count', models.IntegerField(default=0, verbose_name='Ko‘rishlar soni')),
                ('vacancy_status', models.BooleanField(default=True, verbose_name='Vakansiya holati')),
            ],
            options={
                'db_table': 'pr_vacancies',
                'ordering': ('-vacancy_datetime',),
            },
        ),
        migrations.CreateModel(
            name='VideoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
            ],
            options={
                'db_table': 'gallery_videos_links',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title_uz', models.CharField(max_length=255, verbose_name='Fotogalereya sarlavhasi')),
                ('gallery_title_en', models.CharField(max_length=255, verbose_name='Title photogallery')),
                ('gallery_title_ru', models.CharField(max_length=255, verbose_name='Названия фотогалерея')),
                ('gallery_desc_uz', models.CharField(max_length=500, verbose_name='Fotogalereya qisqacha tavsifi')),
                ('gallery_desc_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Photogallery description')),
                ('gallery_desc_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание фотогалерея')),
                ('gallery_datetime', models.DateTimeField(auto_now_add=True)),
                ('gallery_views_count', models.IntegerField(default=0, verbose_name='Ko‘rishlar soni')),
                ('gallery_images', models.ManyToManyField(to='app_piar.image')),
            ],
            options={
                'db_table': 'pr_photogallery',
                'ordering': ('-gallery_datetime',),
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title_uz', models.CharField(max_length=255, verbose_name='Videogalereya sarlavhasi')),
                ('gallery_title_en', models.CharField(max_length=255, verbose_name='Title videogallery')),
                ('gallery_title_ru', models.CharField(max_length=255, verbose_name='Названия видеогалерея')),
                ('gallery_desc_uz', models.CharField(max_length=500, verbose_name='Videogalereya qisqacha tavsifi')),
                ('gallery_desc_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Videogallery description')),
                ('gallery_desc_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание видеогалерея')),
                ('gallery_datetime', models.DateTimeField(auto_now_add=True)),
                ('gallery_views_count', models.IntegerField(default=0, verbose_name='Ko‘rishlar soni')),
                ('gallery_videos', models.ManyToManyField(to='app_piar.videolinks')),
            ],
            options={
                'db_table': 'pr_videogallery',
                'ordering': ('-gallery_datetime',),
            },
        ),
    ]
